import os
import pytest
from fastapi.testclient import TestClient
from app.main import app
from app.config import settings

client = TestClient(app)

HAS_GEMINI_KEY = bool(settings.gemini_api_key)

def test_analyze_no_input():
    response = client.post("/api/analyze")
    assert response.status_code == 400
    assert response.json()["detail"] == "Either image or text must be provided"

@pytest.mark.skipif(HAS_GEMINI_KEY, reason="This test is for when Gemini key is missing")
def test_analyze_missing_gemini_key():
    response = client.post("/api/analyze", data={"text": "Test observation"})
    assert response.status_code == 400
    assert "Gemini API key not configured" in response.json()["detail"]

@pytest.mark.skipif(not HAS_GEMINI_KEY, reason="Requires real Gemini API credentials")
def test_analyze_valid_observation():
    # The expected scenario from the prompt
    text_input = "Machine M104 checked today. Temperature 82°C. Vibration is high. Oil looks okay. Filter needs changing. Check again next week."
    
    response = client.post("/api/analyze", data={"text": text_input})
    assert response.status_code == 200, f"API failed: {response.text}"
    
    data = response.json()
    
    # Verify the canonical schema fields
    assert data["machine_id"] == "M104"
    assert "next week" in data["next_inspection"].lower()
    
    # We expect readings for temperature, vibration, oil_level, filter
    readings = {r["parameter"]: r for r in data["readings"]}
    
    assert "temperature" in readings
    assert readings["temperature"]["value"] == 82.0
    
    assert "vibration" in readings
    assert readings["vibration"]["status"] == "HIGH"
    
    assert "oil_level" in readings
    assert readings["oil_level"]["status"] == "NORMAL"
    
    assert "filter" in readings
    assert readings["filter"]["status"] == "REPLACEMENT_REQUIRED"
    
    # The validation engine should run after extraction and see vibration HIGH -> at least HIGH priority
    assert data["risk_priority"] in ["HIGH", "CRITICAL"]
    
    # Recommendations should be generated by the Gemini model
    assert len(data["recommended_actions"]) > 0
    assert any("vibration" in r["action"].lower() or "filter" in r["action"].lower() for r in data["recommended_actions"])
    
    # Verify persistence mock fields are there
    assert "inspection_id" in data
    assert "created_at" in data

@pytest.mark.skipif(not HAS_GEMINI_KEY, reason="Requires real Gemini API credentials")
def test_analyze_ambiguous_observation():
    # The unusual scenario from the prompt
    text_input = "Machine M104 temperature 820°C."
    
    response = client.post("/api/analyze", data={"text": text_input})
    assert response.status_code == 200, f"API failed: {response.text}"
    
    data = response.json()
    
    assert data["machine_id"] == "M104"
    
    readings = {r["parameter"]: r for r in data["readings"]}
    assert "temperature" in readings
    temp_reading = readings["temperature"]
    
    assert temp_reading["value"] == 820.0
    
    # Our deterministic engine (app.services.validation_service) enforces max temp 500
    # The engine should flag this value as uncertain and add a warning
    assert temp_reading["is_uncertain"] is True
    assert temp_reading["confidence"] <= 0.3
    
    warnings = data.get("warnings", [])
    assert any(w["field"] == "temperature" and "plausible range" in w["message"].lower() for w in warnings)
